# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  empapi:
    image: rsbnhyd/employeeapi
    container_name: empapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Raj@MDPR1
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - 8999:80
      - 9443:443
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - sqldb
  webclient:
    image: rsbnhyd/empwebclient
    container_name: empwebclient
    ports:
      - 8998:8998
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_ENVIRONMENT=Production
    depends_on:
      - sqldb
      - empapi
  sqldb:
    image: rsbnhyd/sqlserver
    container_name: sqldb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Raj@MDPR1
    volumes:
      - /e/sql/data:/var/opt/mssql/data:rw
    ports:
      - 1433:1433
