apiVersion: apps/v1
kind: Deployment
metadata:
  name: emp
  namespace: rsb.emp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: empapi
  template:
    metadata:
      labels:
        app: empapi
    spec:
      containers:
        - name: empapi
          image: rsbnhyd/employeeapi
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: emp
  namespace: rsb.emp
spec:
  selector:
    app: empapi
  type: ClusterIP
  ports:
    - name: empapi
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
---

